version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - FAL_KEY=${FAL_KEY}
      - PORT=3001
      - NODE_ENV=production